name: Colcon build and test (Windows)

on: 
  workflow_dispatch:

jobs:
  build_and_test:
    strategy:
      matrix:
        ros_distribution:
          - foxy
    name: build_and_test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: ros-tooling/setup-ros@0.1.3
        with:
            required-ros-distributions: ${{ matrix.ros_distribution }}
      - run: mkdir c:\opt\chocolatey
      - run: set ChocolateyInstall=c:\opt\chocolatey
      - run: choco source add -n=ros-win -s="https://aka.ms/ros/public" --priority=1
      - run: choco upgrade ros-foxy-desktop -y --execution-timeout=0
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: diffbot2_simulation
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: "${{ github.workspace }}/diffbot2.repos"
