name: Colcon build and test

on: 
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    name: build_and_test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.0.25
      - uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: diffbot2_simulation
          target-ros2-distro: foxy
          vcs-repo-file-url: "${{ github.workspace }}/diffbot2.repos"