name: Ament Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ament_lint:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    name: ament_lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [xmllint, lint_cmake, copyright]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.0.25
      - uses: ros-tooling/action-ros-lint@master
        with:
          distribution: foxy
          linter: ${{ matrix.linter }}
          package-name:
            diffbot2_simulation
